const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: '120',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'pants',
      image: '/images/p2.jpg',
      price: '150',
      countInStock: 15,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'Adidas-slim-shirt',
      category: 'shirts',
      image: '/images/p3.jpg',
      price: '250',
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Slim Pant',
      slug: 'Adidas-slim-pant',
      category: 'pants',
      image: '/images/p4.jpg',
      price: '300',
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};

export default data;
